add orm
TeamHSE/study-platform pull request #30
Opened 2024-06-08 12:54 UTC by disk0Dancer

add orm entities

2024-06-08 16:00 UTC, AleksanderNekr commented
Я сейчас develop сделаю главной, чтоб никто не путался

2024-06-08 16:21 UTC, AleksanderNekr requested changes

2024-06-08 16:21 UTC, AleksanderNekr commented on backend/src/db.ts
> +  database: "courses",
Лучше кнш это из переменных среды брать, которые в docker-compose можно определить, чтобы потом легко сменить на продовые данные, а не в коде их писать, чтобы опять в гитхаб не отправлять)

2024-06-08 16:21 UTC, AleksanderNekr commented on backend/src/entity/User.ts
> +// }
Закоменченный код лучше убирать из гита)

2024-06-08 16:21 UTC, AleksanderNekr commented on backend/src/controllers/UserController.ts
> +      return res;
Интересный способ в одном методе обрабатывать сразу и пост и гет, но по мне так лучше отдельно, но оставь так, если это так принято

2024-06-08 16:21 UTC, AleksanderNekr commented on backend/ormconfig.json
> +  "type": "postgres",
Мб есть способ получать свойства подключения из переменных среды, чтобы не хардкодить их снова, когда база продовая будет и в гитхаб не сливать данные
Например, задавать переменные среды через docker-compose, а в коде их доставать


Посмотрел, вроде можно
https://stackoverflow.com/questions/62143322/typeorm-config-with-env-variables

2024-06-08 16:24 UTC, disk0Dancer commented on backend/src/db.ts
> +  database: "courses",
Да я знаю, просто пока дев версия и нет реальных данных, я решил забить и потом пофиксить все такие проблемы.

2024-06-08 16:26 UTC, AleksanderNekr commented on backend/src/db.ts
> +  database: "courses",
Окей, пока пропустим тогда это

2024-06-08 16:27 UTC, AleksanderNekr commented on backend/ormconfig.json
> +  "type": "postgres",
Это тогда тоже на потом

2024-06-08 16:27 UTC, disk0Dancer commented on backend/ormconfig.json
> +  "type": "postgres",
Да, я настроил уже конфиг, просто допилю конфиг походу работы, там отдельную веточку бы сделать, чтобы его нарм закодить

2024-06-08 16:30 UTC, AleksanderNekr commented on backend/ormconfig.json
> +  "type": "postgres",
> Да, я настроил уже конфиг, просто допилю конфиг походу работы, там отдельную веточку бы сделать, чтобы его нарм закодить

Ок, можешь потом себе в бэклог сделать на потом

2024-06-08 16:47 UTC, AleksanderNekr commented
Кстати потом на будущее надо будет с ОРМкой хотя бы 1 интеграционный тест с бд сделать по требованиям проекта

2024-06-10 04:44 UTC, AleksanderNekr approved these changes

2024-06-10 04:45 UTC, merged

2024-06-10 04:47 UTC, AleksanderNekr reviewed
@ZakharMolchanov, лучше в след раз, если тебе нужен чей-то код для своей фичи, то не коммитить прямо в ветку другой фичи, а делать от нее ответвление, чтоб после пр я мог спокойно снести закрытую фиче-ветку