Feat/compose db
TeamHSE/study-platform pull request #36
Opened 2024-06-13 14:30 UTC by disk0Dancer

[x] added db container
[x] set up networking front-back

TODO: compress docker images:
    - backend ~ 900 Mb
    - frontend ~ 400 Mb

2024-06-13 14:32 UTC, AleksanderNekr commented on compose.yaml
> +networks:
Оставил сети)) Ладно, пусть будут

2024-06-13 14:33 UTC, AleksanderNekr commented on backend/Dockerfile
> +ARG NODE_VERSION=21.6.1
Вообще сами разрабы ноды не советуют совать не LTS-версии в прод, но это если душить
Пусть будет

2024-06-13 15:00 UTC, disk0Dancer commented on backend/Dockerfile
> +ARG NODE_VERSION=21.6.1
окей, учту, я не думал об этом

2024-06-13 15:04 UTC, AleksanderNekr requested changes
У меня бэк не запустился
![image](https://github.com/TeamHSE/study-platform/assets/59678267/1df37a44-267c-41e7-bcc3-426379885008)

У тебя по `docker compose up build` норм?

2024-06-13 15:07 UTC, AleksanderNekr commented on backend/Dockerfile
>  ARG PNPM_VERSION=9.0.2
Кстати pnpm можно убрать, так как ты собираешь по npm

2024-06-13 15:47 UTC, disk0Dancer commented
> У меня бэк не запустился ![image](https://private-user-images.githubusercontent.com/59678267/339418093-1df37a44-267c-41e7-bcc3-426379885008.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTgyOTM3NjQsIm5iZiI6MTcxODI5MzQ2NCwicGF0aCI6Ii81OTY3ODI2Ny8zMzk0MTgwOTMtMWRmMzdhNDQtMjY3Yy00MWU3LWJjYzMtNDI2Mzc5ODg1MDA4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjEzVDE1NDQyNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTY3MzZiMGEzMTdkNjE5NWYxMDY3NDEyZjA5YmU4N2QyYzlkMDU3NDQ5MjY1ZTY1NWRmOTdiYjZiZWVlODhmYjcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.wed1j1eFDj3XMtRizTln1tpuiCPeRRXFvWGnJyIxHNE)
> 
> У тебя по `docker compose up --build` норм?

блен, короче баг какой то вылез, на стаковерфлоу отдельная ветка есть, я посмотрю, у меня тоже не билдится.. локально работает

2024-06-14 07:32 UTC, disk0Dancer commented on backend/Dockerfile
>  ARG PNPM_VERSION=9.0.2
убрал

2024-06-14 07:33 UTC, disk0Dancer commented
- пофиксил баг со сборкой докера (убрал пакет)
- дилигировали хэширование пароля на фронт

2024-06-14 07:36 UTC, AleksanderNekr commented
> * пофиксил баг со сборкой докера (убрал пакет)
> * делегировали хэширование пароля на фронт

А чем обусловлено решение хешировать на фронте? По-моему, такая логика происходит всегда на бэке, фронт вызывает апишку входа с телом логином/паролем, обратно получает jwt-токен

2024-06-14 07:37 UTC, AleksanderNekr commented
> > * пофиксил баг со сборкой докера (убрал пакет)
> > * делегировали хэширование пароля на фронт
> 
> А чем обусловлено решение хешировать на фронте? По-моему, такая логика происходит всегда на бэке, фронт вызывает апишку входа с телом логином/паролем, обратно получает jwt-токен

Я кнш понимаю, что можно на нексте серверный компонент заюзать, но это уже 2 бэка получатся
Лучше на бэке оставить хеширование @ZakharMolchanov 
https://security.stackexchange.com/questions/54095/when-and-where-do-i-hash-a-password

2024-06-14 07:43 UTC, AleksanderNekr commented
> > > * пофиксил баг со сборкой докера (убрал пакет)
> > > * делегировали хэширование пароля на фронт
> > 
> > 
> > А чем обусловлено решение хешировать на фронте? По-моему, такая логика происходит всегда на бэке, фронт вызывает апишку входа с телом логином/паролем, обратно получает jwt-токен
> 
> Я кнш понимаю, что можно на нексте серверный компонент заюзать, но это уже 2 бэка получатся Лучше на бэке оставить хеширование @ZakharMolchanov https://security.stackexchange.com/questions/54095/when-and-where-do-i-hash-a-password

UPD: Опечатка Гриши, хешируем на бэке)

Для истории

2024-06-14 08:24 UTC, AleksanderNekr approved these changes

2024-06-14 08:24 UTC, merged