Прописал всем id тип UUID + настроил авто генерацию на стороне PG
TeamHSE/study-platform pull request #44
Opened 2024-06-16 18:51 UTC by ZakharMolchanov

2024-06-16 19:02 UTC, ZakharMolchanov commented
Чет чел ругается, из-за файлов. Чекните пж. При авторизации и регистрации выдается в куки JWT токен, шифруется приватником, в пейлоаде передает пока login( токен живет час) .Основная задача jwt токена, это аутентификация( публчиный ключ сгенерен из приватника, можно чекать подпись jwt публичным).

2024-06-16 19:25 UTC, disk0Dancer commented on package.json
> +}
Норм, что packge.json появился там, где у нас нет проекта? 
я, кажется уже у себя удалял пару раз его, хз нужен он нет?

2024-06-16 19:25 UTC, disk0Dancer commented on backend/src/controllers/AuthController.ts
> +      const hashedPassword = await bcrypt.hash(password, 10);
Нет проблем с пакетом при сборке через докер?

2024-06-16 19:25 UTC, disk0Dancer commented on backend/src/controllers/AuthController.ts
> +      }
Мб стоит извлечь код валидации запроса в отдельную функцию?
Будет лучше смотреться, как мне кажется, да и изменения легче будет вносить.

2024-06-16 19:25 UTC, disk0Dancer commented on backend/src/controllers/AuthController.ts
> +        const privateKey = fs.readFileSync('private.pem', 'utf8');
мб стоит загрузить ключ в Config? и читать его из enviroment?

2024-06-16 19:34 UTC, disk0Dancer commented on backend/src/routes.ts
> +  app.post("/api/auth/login", AuthController.login);
Как я понял, предупреждение о том, что при обработке запроса мы лезем в файловую систему, каждый запрос обрабатывается асинхронно и хз как поведет себя программа в стрессе, наверное лучше убрать это дело в конфиг, и загружать через конфиг прикатный ключ.

Можно сделать метод, чтобы не хранить все время ключ в переменной, либо поле и пофиг.

2024-06-16 19:36 UTC, ZakharMolchanov commented on backend/src/controllers/AuthController.ts
> +      const hashedPassword = await bcrypt.hash(password, 10);
Проблем нет, контейнер бэкенда стартует нормально. В БД записывает корректно 
![image](https://github.com/TeamHSE/train-platform/assets/92994381/e9855256-ad72-4c95-96e2-fdbcd868abcd)

2024-06-16 19:37 UTC, ZakharMolchanov commented on backend/src/controllers/AuthController.ts
> +        const privateKey = fs.readFileSync('private.pem', 'utf8');
Я чекал в инете, пишут, что публичный ключ можно в конфиг вынести, а приватный лучше хранить в файле. Но в целом, если проект учебный, то можно вынести все в конфиг

2024-06-16 19:45 UTC, ZakharMolchanov commented on package.json
> +}
Эх, устанавливал пакеты в открытой директории train-platform, а не в backend. Этот package.json не нужен.

2024-06-16 19:48 UTC, ZakharMolchanov commented
Прошу не чекать( надо бы его отменить) коммит #3a0594c3f95e5d4934e83afe647f954b0f9e6bab, неверно указаны типы данных

2024-06-16 19:49 UTC, ZakharMolchanov commented on backend/src/controllers/AuthController.ts
> +      }
Да, согласен. Исправлю

2024-06-16 19:50 UTC, disk0Dancer commented on package.json
> +}
Панимаю, убери пж потом в след комите, перед слияним.

2024-06-16 19:51 UTC, disk0Dancer commented on backend/src/controllers/AuthController.ts
> +        const privateKey = fs.readFileSync('private.pem', 'utf8');
Сделай метод для обьекта конфиг, чтобы он просто читал из файла.

Типо доступ в файловой системы из другого метода просто, не из обработчика.

2024-06-16 19:53 UTC, disk0Dancer commented on backend/src/controllers/AuthController.ts
> +      const hashedPassword = await bcrypt.hash(password, 10);
У меня такая фигня выпала 
<img width="564" alt="image" src="https://github.com/TeamHSE/train-platform/assets/89835485/42e1d0fc-4970-47c0-9f5a-df6d85814bac">

2024-06-16 19:54 UTC, ZakharMolchanov commented on backend/src/controllers/AuthController.ts
> +        const privateKey = fs.readFileSync('private.pem', 'utf8');
А окей, сделаю

2024-06-17 08:47 UTC, ZakharMolchanov commented on backend/src/controllers/AuthController.ts
> +      const hashedPassword = await bcrypt.hash(password, 10);
Эта проблема из-за коммита https://github.com/TeamHSE/train-platform/commit/3a0594c3f95e5d4934e83afe647f954b0f9e6bab

2024-06-18 11:45 UTC, AleksanderNekr requested changes

2024-06-18 12:38 UTC, AleksanderNekr requested changes

2024-06-18 12:38 UTC, AleksanderNekr commented on backend/src/controllers/AuthControllerLogin.ts
> +import fs from 'fs';
Лишняя зависимость здесь, проверь

2024-06-18 12:38 UTC, AleksanderNekr commented on backend/src/controllers/AuthControllerLogin.ts
> +      const privateKey = config.readPrivateKey('path/to/private.pem'); // Update with the actual path
Тут что-то не так с путем)

2024-06-18 12:38 UTC, AleksanderNekr commented on backend/src/controllers/AuthControllerLogin.ts
> +    const isPasswordValid = await bcrypt.compare(password, user.password);
Здесь авейт лишний вроде как

2024-06-18 12:38 UTC, AleksanderNekr commented on backend/src/controllers/AuthControllerRegister.ts
> +import * as fs from 'fs';
Здесь фс тоже лишний по идее

2024-06-18 12:38 UTC, AleksanderNekr commented on backend/src/entity/Course.ts
>  @Entity("courses")
Слишком много переносов строки – отформатируй код пж

2024-06-18 12:38 UTC, AleksanderNekr commented on backend/src/entity/CoursesModules.ts
>  @Entity("courses_modules")
Тоже переносов много

2024-06-18 12:38 UTC, AleksanderNekr commented on backend/src/entity/CoursesStep.ts
> +
Переносы

2024-06-18 12:38 UTC, AleksanderNekr commented on backend/src/entity/CoursesViewers.ts
> +
Переносы)

2024-06-18 12:38 UTC, AleksanderNekr commented on backend/src/entity/User.ts
Переносов много

2024-06-18 12:38 UTC, AleksanderNekr commented on backend/src/entity/UsersRoles.ts
> +
Тоже перенос лишний

2024-06-18 13:34 UTC, AleksanderNekr requested changes
Настроить CORS-политику для URL фронта: (localhost:3000, лучше брать из конфига url) на доступ к конечным точкам и пересылки credentials

2024-06-18 13:54 UTC, AleksanderNekr commented
[] Добавить генерацию RSA-ключей в Dockerfile
[] Настроить CORS

2024-06-18 14:54 UTC, AleksanderNekr commented
От меня ОК, @disk0Dancer, посмотри пж

2024-06-18 17:52 UTC, disk0Dancer approved these changes

2024-06-18 18:03 UTC, disk0Dancer requested changes

2024-06-18 18:03 UTC, disk0Dancer commented on backend/src/config/Config.ts
> +const frontendURL = "http://localhost:3001";
- лучше убрать в enviroment
- добавить в compose.yml

2024-06-18 18:03 UTC, disk0Dancer commented on backend/src/config/Config.ts
> +const publicKeyPath = path.resolve('src/public.pem');
перемести файлы в ```backend/src/config```, думаю можно инициализировать прямо к конструкторе.
Только проверь, что .dockerignore не скрывает эти файлы

2024-06-18 18:14 UTC, AleksanderNekr commented on backend/src/config/Config.ts
> +const publicKeyPath = path.resolve('src/public.pem');
Кстати тут решили, что файлы ключей совать в гит не будем, так как это чувствительная информация, в докерфайле бэка добавлена генерация ключей

Чтобы тебе их получить для локальной разработки без докера, можешь у Захара их попросить, или сгенерить

2024-06-18 19:51 UTC, disk0Dancer commented on backend/src/config/Config.ts
> +const publicKeyPath = path.resolve('src/public.pem');
Хорошее предложение, добавьте инструкцию к запуску(генерации) пж

2024-06-18 20:33 UTC, ZakharMolchanov commented on backend/src/config/Config.ts
> +const publicKeyPath = path.resolve('src/public.pem');
в енвайромент закинул пути
генерятся ключи в src/config

2024-06-18 20:37 UTC, disk0Dancer approved these changes

2024-06-19 06:41 UTC, AleksanderNekr approved these changes

2024-06-19 06:41 UTC, merged